---
- name: Creating the users
  user:
   name: "{{ $name }}"
   password: "{{ 'rastor' | password_harsh('sha512') }}"
   comment: "{{ $full }}"
   shell: /bin/bash
   group: wheel
   groups: wheel
   home: /home/"{{ $name }}"
